using CentralIdentity.Application.Common.Interfaces;
using System.Security.Cryptography;
using System.Text;

namespace CentralIdentity.Infrastructure.Security;

/// <summary>
/// Hashes OAuth client secrets. Client secrets are already cryptographically random and
/// high-entropy (generated by <c>ApplicationService</c>), but we still apply a salted
/// PBKDF2-HMAC-SHA256 derivation (lighter iteration count than user passwords is
/// appropriate given the input's entropy) so a stolen secret hash can never be reversed
/// or reused as a lookup key.
/// Stored format: v1$&lt;base64 salt&gt;$&lt;base64 hash&gt;$&lt;iterations&gt;
/// </summary>
public sealed class Pbkdf2ClientSecretHasher : IClientSecretHasher
{
    private const int Iterations = 100_000;
    private const int SaltSize = 16;
    private const int HashSize = 32;
    private static readonly HashAlgorithmName Algorithm = HashAlgorithmName.SHA256;

    public string HashSecret(string secret)
    {
        var salt = RandomNumberGenerator.GetBytes(SaltSize);
        var hash = Rfc2898DeriveBytes.Pbkdf2(
            Encoding.UTF8.GetBytes(secret),
            salt,
            Iterations,
            Algorithm,
            HashSize);
        return $"v1${Convert.ToBase64String(salt)}${Convert.ToBase64String(hash)}${Iterations}";
    }

    public bool VerifySecret(string secret, string hash)
    {
        try
        {
            var parts = hash.Split('$');
            if (parts.Length != 4 || parts[0] != "v1") return false;
            var salt = Convert.FromBase64String(parts[1]);
            var expectedHash = Convert.FromBase64String(parts[2]);
            if (!int.TryParse(parts[3], out var iterations) || iterations < 1) return false;
            var actualHash = Rfc2898DeriveBytes.Pbkdf2(
                Encoding.UTF8.GetBytes(secret),
                salt,
                iterations,
                Algorithm,
                HashSize);
            return CryptographicOperations.FixedTimeEquals(actualHash, expectedHash);
        }
        catch (FormatException)
        {
            return false;
        }
    }
}
